### ISSUE TITLE
Alllocate dynamic memory

### ISSUE THREAD

**Issue by freiurs** [fisothemes/TwinCat-Dynamic-Collections#2]
If the memory allocation failes, no error is thrown and bSuccess is set to TRUE. There is no feedback for the user that the object was not saved in the collection.
![image](https://github.com/fisothemes/TwinCat-Dynamic-Collections/assets/57216920/1945d96b-25ce-4dd9-8a56-e8cb32e810af)

**Comment by fisothemes** [comment]
Hi @freiurs thanks for bringing this to my attention. 

Thank you for bringing this to my attention. I will look into this issue and make the necessary changes.

If you have encountered this issue in the past, it would be helpful if you could provide more details. The documentation on Beckhoff's website does not provide much information on how or why memory allocation can fail. The only case I can think of is when the router memory pool has been exhausted. Codesys' documentation alludes to the fact that it may fail if two tasks try to allocate memory at the same time, but this is not mentioned in Beckhoff's documentation.

It is also worth noting that functions like F_Clone_Generic(...) may not include the error check in the future. This is because it is better for the user to explicitly check for errors, as this allows for more flexibility and keeps the code D.R.Y. However, the functions are still open for use, and I encourage you to use them with care.

Thanks again 👍

[Codesys docs on __NEW](https://help.codesys.com/api-content/2/codesys/3.5.12.0/en/_cds_operator_new/)
[Beckhoff docs on __NEW](https://infosys.beckhoff.com/content/1033/tc3_plc_intro/2529171083.html?id=5409766235804740463)
[Beckhoff docs on Router memory](https://infosys.beckhoff.com/content/1033/tf7xxx_tc3_vision/6797114507.html?id=5557377509594186908)

**Comment by freiurs** [comment]
Hey @fisothemes 
Yes the two cases you mentioned when the allocation can fail are also the cases i know.
I would suggest to just checkif the pointer is not null when calling the function. Otherwise the bSuccess can be set to FALSE.
Anyway, your Lib is very usefull!
Thanks a lot

**Comment by fisothemes** [comment]
Hi @freiurs 
I have now implemented this. See pre-release [v1.0.4.21 ](https://github.com/fisothemes/TwinCat-Dynamic-Collections/releases/tag/v1.0.4.21).

Thanks again for bring this issue up 👍.
